// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace PortAudioCSharp.AutoGenerated
{
    public static unsafe partial class NativeConsts
    {


        public const uint paFormatIsSupported = 0;
        public const uint paFramesPerBufferUnspecified = 0;



    }


    public enum PaErrorCode : int
    {
        paNoError = 0,
        paNotInitialized = -10000,
        paUnanticipatedHostError = -9999,
        paInvalidChannelCount = -9998,
        paInvalidSampleRate = -9997,
        paInvalidDevice = -9996,
        paInvalidFlag = -9995,
        paSampleFormatNotSupported = -9994,
        paBadIODeviceCombination = -9993,
        paInsufficientMemory = -9992,
        paBufferTooBig = -9991,
        paBufferTooSmall = -9990,
        paNullCallback = -9989,
        paBadStreamPtr = -9988,
        paTimedOut = -9987,
        paInternalError = -9986,
        paDeviceUnavailable = -9985,
        paIncompatibleHostApiSpecificStreamInfo = -9984,
        paStreamIsStopped = -9983,
        paStreamIsNotStopped = -9982,
        paInputOverflowed = -9981,
        paOutputUnderflowed = -9980,
        paHostApiNotFound = -9979,
        paInvalidHostApi = -9978,
        paCanNotReadFromACallbackStream = -9977,
        paCanNotWriteToACallbackStream = -9976,
        paCanNotReadFromAnOutputOnlyStream = -9975,
        paCanNotWriteToAnInputOnlyStream = -9974,
        paIncompatibleStreamHostApi = -9973,
        paBadBufferPtr = -9972,
        paCanNotInitializeRecursively = -9971,
    }

    public enum PaHostApiTypeId : uint
    {
        paInDevelopment = 0,
        paDirectSound = 1,
        paMME = 2,
        paASIO = 3,
        paSoundManager = 4,
        paCoreAudio = 5,
        paOSS = 7,
        paALSA = 8,
        paAL = 9,
        paBeOS = 10,
        paWDMKS = 11,
        paJACK = 12,
        paWASAPI = 13,
        paAudioScienceHPI = 14,
        paAudioIO = 15,
        paPulseAudio = 16,
        paSndio = 17,
    }

    public enum PaStreamCallbackResult : uint
    {
        paContinue = 0,
        paComplete = 1,
        paAbort = 2,
    }


}
