using System.Reflection;
using System.Runtime.InteropServices;
using PortAudioCSharp.AutoGenerated;
using PortAudioCSharp.Services;
using PortAudioCSharp.Wrapper;

NativeLibrary.SetDllImportResolver(typeof(NativeConsts).Assembly, DllImportResolver);
Console.WriteLine(PortAudioWrapper.GetVersionText());

using var service = new PortAudioService();

var hostApi = service.DefaultHostApi;
Console.WriteLine(hostApi.Name);

var device = service.DefaultOutputDevice;
Console.WriteLine(device.Name);

using var parameter = new StreamParameters(device._deviceIndex, 2, (nuint)PaSampleFormat.paInt16, device.DefaultLowOutputLatency);
using var stream = new PortAudioOutStrem(device._deviceIndex, parameter, 44100, PaStreamFlags.paNoFlag, new WaveFileReader(args[0]).Stream);
stream.Start();
await Task.Delay(3*60*1000);

static IntPtr DllImportResolver(string libraryName, Assembly assembly, DllImportSearchPath? searchPath)
{
    if (libraryName == "portaudio")
    {
        string path = "";
        string modifier = "lib";
        string extention = "";
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
        {
            path += "/usr/lib";
            extention = ".so.2";
        }

        if (RuntimeInformation.ProcessArchitecture == Architecture.X86 || RuntimeInformation.ProcessArchitecture == Architecture.X64)
        {
            path += "/x86_64-linux-gnu";
        }

        return NativeLibrary.Load(Path.Combine(path, $"{modifier}portaudio{extention}"), assembly, searchPath);
    }

    // Otherwise, fallback to default import resolver.
    return IntPtr.Zero;
}
