using System;
using System.Runtime.CompilerServices;
using PortAudioCSharp.AutoGenerated;
using PortAudioCSharp.Exceptions;
using PortAudioCSharp.Utils;

namespace PortAudioCSharp.Wrapper;

public static class PortAudioWrapper
{
    public static unsafe string GetVersionText()
    {
        return Helper.ConvertText(NativeMethods.Pa_GetVersionText());
    }

    public static unsafe VersionInfo GetVersionInfo()
    {
        return new VersionInfo(NativeMethods.Pa_GetVersionInfo());
    }

    public static void Initialize()
    {
        PortAudioException.ThrowIfError(NativeMethods.Pa_Initialize());
    }

    public static void Terminate()
    {
        PortAudioException.ThrowIfError(NativeMethods.Pa_Terminate());
    }

    public static unsafe string GetErrorText(PaErrorCode errorCode)
    {
        return Helper.ConvertText(NativeMethods.Pa_GetErrorText((int)errorCode));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int GetHostApiCount()
    {
        return NativeMethods.Pa_GetHostApiCount();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int GetDefaultHostApi()
    {
        return NativeMethods.Pa_GetDefaultHostApi();
    }

    public static unsafe HostApiInfo GetHostApiInfo(int hostApi)
    {
        var paHostApiInfo = NativeMethods.Pa_GetHostApiInfo(hostApi);
        if ((nint)paHostApiInfo != nint.Zero)
        {
            return new HostApiInfo(paHostApiInfo);
        }
        else
        {
            return default;
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int HostApiTypeIdToHostApiIndex(PaHostApiTypeId type)
    {
        return NativeMethods.Pa_HostApiTypeIdToHostApiIndex(type);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int HostApiDeviceIndexToDeviceIndex(int hostApi, int hostApiDeviceIndex)
    {
        return NativeMethods.Pa_HostApiDeviceIndexToDeviceIndex(hostApi, hostApiDeviceIndex);
    }

    public static unsafe HostErrorInfo GetLastHostErrorInfo()
    {
        return new HostErrorInfo(NativeMethods.Pa_GetLastHostErrorInfo());
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int GetDefaultInputDevice()
    {
        return NativeMethods.Pa_GetDefaultInputDevice();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int GetDefaultOutputDevice()
    {
        return NativeMethods.Pa_GetDefaultOutputDevice();
    }

    public static unsafe DeviceInfo GetDeviceInfo(int deviceIndex)
    {
        var info = NativeMethods.Pa_GetDeviceInfo(deviceIndex);
        if ((nint)info == nint.Zero)
        {
            return default;
        }
        return new DeviceInfo(info);
    }

    public static int GetDeviceCount()
    {
        return NativeMethods.Pa_GetDeviceCount();
    }

    public static unsafe bool IsFormatSupported(StreamParameters? inputParameters, StreamParameters? outputParameters, double sampleRate)
    {
        int ret;
        if (inputParameters == null && outputParameters == null)
        {
#pragma warning disable CA2208 // Instantiate argument exceptions correctly
            throw new ArgumentNullException($"At least one of {nameof(inputParameters)} or {nameof(outputParameters)} must be non-null");
#pragma warning restore CA2208 // Instantiate argument exceptions correctly
        }
        else if (inputParameters == null)
        {
            var parameter = outputParameters!.ToPaStreamParameters();
            ret = NativeMethods.Pa_IsFormatSupported((PaStreamParameters*)nint.Zero, &parameter, sampleRate);
        }
        else if (outputParameters == null)
        {
            var parameter = inputParameters!.ToPaStreamParameters();
            ret = NativeMethods.Pa_IsFormatSupported(&parameter, (PaStreamParameters*)nint.Zero, sampleRate);
        }
        else
        {
            var input = inputParameters.ToPaStreamParameters();
            var output = outputParameters.ToPaStreamParameters();
            ret = NativeMethods.Pa_IsFormatSupported(&input, &output, sampleRate);
        }

        return ret == NativeConsts.paFormatIsSupported;
    }
}
